baseURL = "https://rainbowcrow.com/"
languageCode = "en-us"
title = "Rainbow Crow"
theme = "lime"
GoogleAnalytics = "G-BTWNF48RZS"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
